In [1]:
from sklearn import svm
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score , accuracy_score

In [2]:
optdigitstrain = pd.read_csv(r'/home/mucahit/Desktop/optdigits.tra', 
                        header = None)

In [3]:
optdigitstest = pd.read_csv(r'/home/mucahit/Desktop/optdigits.tes',
                        header = None)

In [4]:
X_train = optdigitstrain.drop(64, axis=1)
y_train = optdigitstrain[64]
X_test = optdigitstest.drop(64, axis=1)
y_test = optdigitstest[64]

In [5]:
#en düşük accuracy 8 de bulunduğu için

for i in range(len(y_train)):
    if y_train[i] == 8:
        y_train[i] = 1
    else:
        y_train[i] = 0

for i in range(len(y_test)):
    if y_test[i] == 8:
        y_test[i] = 1
    else:
        y_test[i] = 0


In [13]:
for degree in range(1, 6):
    SVM = svm.SVC(kernel="poly", degree=degree, gamma='scale')
    SVM.fit(X_train, y_train)
    SVMy_pred = SVM.predict(X_test)

    print('SVM Accuracy for {}. Degree Polynomial = {}'.format(
            degree,
            round(accuracy_score(SVMy_pred, y_test),5)
        )
    )
    
    print(
        'Confusion Matrix for {}. degree Polynomial =\n {}'.format(
            degree,
            confusion_matrix(y_test, SVMy_pred)
        )
    )
    print(
        'AUC Score for {}. degree Polynomial = {}'.format(
            degree,
            round(roc_auc_score(y_test, SVMy_pred), 5)
        )
    )

SVM Accuracy for 1. Degree Polynomial = 0.96049
Confusion Matrix for 1. degree Polynomial =
 [[1612   11]
 [  60  114]]
AUC Score for 1. degree Polynomial = 0.8242
SVM Accuracy for 2. Degree Polynomial = 0.98442
Confusion Matrix for 2. degree Polynomial =
 [[1620    3]
 [  25  149]]
AUC Score for 2. degree Polynomial = 0.92724
SVM Accuracy for 3. Degree Polynomial = 0.98831
Confusion Matrix for 3. degree Polynomial =
 [[1620    3]
 [  18  156]]
AUC Score for 3. degree Polynomial = 0.94735
SVM Accuracy for 4. Degree Polynomial = 0.98887
Confusion Matrix for 4. degree Polynomial =
 [[1619    4]
 [  16  158]]
AUC Score for 4. degree Polynomial = 0.95279
SVM Accuracy for 5. Degree Polynomial = 0.98831
Confusion Matrix for 5. degree Polynomial =
 [[1620    3]
 [  18  156]]
AUC Score for 5. degree Polynomial = 0.94735
